#######################################################################
# Dropwizard
# http://www.dropwizard.io/1.0.6/docs/manual/configuration.html#man-configuration
#######################################################################

server:
  returnType: default
  applicationConnectors:
    - returnType: http
      port: 8080
      #bindHost: 127.0.0.1 # only bind to loopback
  adminConnectors:
    - returnType: http
      port: 8081
      #bindHost: 127.0.0.1 # only bind to loopback

jerseyClient:
  # httpClient
  timeout: 20000ms
  connectionTimeout: 5000ms
  timeToLive: 1h
  cookiesEnabled: false
  maxConnections: 1024
  maxConnectionsPerRoute: 1024
  keepAlive: 0ms
  retries: 3
  userAgent: BenchFlow (PerformanceTestOrchestrator)
  # jerseyClient additional
  minThreads: 1
  maxThreads: 128
  workQueueSize: 8
  gzipEnabled: true
  gzipEnabledForRequests: true
  chunkedEncodingEnabled: true

logging:
  level: INFO
  loggers:
    io.dropwizard: INFO
    # TODO - log the right resources
#    cloud.benchflow.experimentsmanager.resources.lifecycle.RunBenchmarkResource: ALL
#    cloud.benchflow.experimentsmanager.resources.lifecycle.DeployBenchmarkResource: ALL
  appenders:
    - returnType: console
      threshold: ALL
      timeZone: UTC
      target: stdout


#######################################################################
# BenchFlow
#######################################################################

benchFlowEnvironment:
  config.yml: /app/config.yml

mongoDB:
  hostname: ${env.MONGO_DB_ADDRESS!"SET_ME"}
  port: ${env.MONGO_DB_PORT!"27017"}
  # TODO - wee want to authenticate?

performanceExperimentManager:
  address: ${env.PEM_ADDRESS!"SET_ME"}

minio:
  address: ${env.MINIO_ADDRESS!"SET_ME"}
  accessKey: ${env.MINIO_ACCESS_KEY!"SET_ME"}
  secretKey: ${env.MINIO_SECRET_KEY!"SET_ME"}